create table fact_user(
	user_id VARCHAR(22) primary KEY,
	name VARCHAR(255) not NULL,
	review_count INT,
	yelping_since TIMESTAMP,
	useful INT,
	funny INT,
	cool INT,
	fans INT,
	friends_count INT,
	average_stars NUMERIC,
	compliment_hot INT,
	compliment_more INT,
	compliment_profile INT,
	compliment_cute INT,
	compliment_list INT,
	comliment_note INT,
	compliment_plain INT,
	compliment_cool INT,
	compliment_funny INT,
	compliment_writer INT,
	compliment_photos INT
)