create table raw_user(
	user_id VARCHAR(255),
	name VARCHAR(255),
	review_count VARCHAR(255),
	yelping_since VARCHAR(255),
	useful VARCHAR(255),
	funny VARCHAR(255),
	cool VARCHAR(255),
	elite TEXT,
	friends TEXT,
	fans VARCHAR(255),
	average_stars VARCHAR(255),
	compliment_hot VARCHAR(255),
	compliment_more VARCHAR(255),
	compliment_profile VARCHAR(255),
	compliment_cute VARCHAR(255),
	compliment_list TEVARCHAR(255)XT,
	comliment_note VARCHAR(255),
	compliment_plain VARCHAR(255),
	compliment_cool VARCHAR(255),
	compliment_funny VARCHAR(255),
	compliment_writer VARCHAR(255),
	compliment_photos VARCHAR(255)
)
